### PR TITLE
fix 404 not found

### PR DESCRIPTION
**Pull request by itslukej**
Title says it all

### CODE REVIEW

**Comment by itslukej** [comment]
I'll look later, This was more of a workaround (that worked for me) until spry fixed it

**Comment by itslukej** [comment]
Also, is it when you are editing or adding a network?

**Comment by DerEnderKeks** [comment]
Both, but if try to edit a network (with `name="name"`) it says 

> No such username or network

**Comment by itslukej** [comment]
Same happens with me, I was only focusing on adding a network. When i have time I will do some major bug fixes

**Comment by itslukej** [comment]
May be because of my/your znc version

**Comment by DerEnderKeks** [comment]
I'm using ZNC 1.6.2.

**Comment by sprybear** [comment]
Sorry to the late one, guys/gals. Fixed. Switched back to `name` value.

**Pull request merged**
